* Introduction
Hi there. Anak's asked me to give a
presentation for his classmates at FAU. My
name is Shane. I'm a software engineer working
in New Zealand. I've been working with Anak on
my project Pen.el for the last year and a half
and I'd like to talking about the Pen.el
project for you today.
- theory
- practical
- future blockchain applications
* Pen.el paper
** What are prompts?
Prompting is querying for generated responses from an AI model.
** Pen.el project - Prompt engineering in emacs
*** What is Pen.el?
- When a prompt function is run from Pen.el, the user is queried for inputs, the query is sent to the AI and its response is captured and then used
- You can use Pen.el to:
  - engineer your own prompt functions
  - extend Pen.el with prompt functions
  - as a prompting server to serve other applications
*** Built-in library of prompt functions 
- http://github.com/semiosis/prompts
library
http://github.com/semiosis/prompts/blob/master/prompts/code-generator-from-description-1.prompt
$PROMPTS/code-generator-from-description-1.prompt

http://github.com/semiosis/prompts/blob/master/prompts/autofix-code-2.prompt
$PROMPTS/autofix-code-2.prompt

http://github.com/semiosis/prompts/blob/master/prompts/asktutor-3.prompt
$PROMPTS/asktutor-3.prompt

*** How to build your own prompt functions

*** Using prompts
**** For coding assistance
***** How to use
#+BEGIN_SRC emacs-lisp -n :async :results verbatim code
  (define-key pen-map (kbd "M-SPC e f") 'pf-get-an-example-of-the-usage-of-a-function/2)
#+END_SRC

pind:/root/.emacs.d/host/ilambda/hs/src/Main.hs

**** As a learning tool
***** Apostrope
***** Paracosm

** Blockchain
*** DAO
*** Currency
*** NFTs