* Introduction
Hello. Anak has asked me to give a presentation for his classmates at FAU. My
name is Shane. I'm a software engineer working in New Zealand. I've been working with Anak on
my project Pen.el for the last year and a half and I'd like to talk about Pen.el for you today.

Pen.el is an IDE for designing prompts, especially language model prompts; Language models such as GPT-3.

* What are prompts?
Prompts in the context of AI are queries to an AI.

The word 'prompt' is borrowed from the way it has been used in the past.

The computer prompts a human for a response with a typical bash prompt:
#+BEGIN_SRC text -n :async :results verbatim code
  root@pen-mele:~$
#+END_SRC

The human responds:
#+BEGIN_SRC text -n :async :results verbatim code
  root@pen-mele:~$ echo Hello computer!
#+END_SRC

Likewise, we can programmatically ask the user
of a software application for a response. This
is called prompting the user.
#+BEGIN_SRC bash -n :i bash :async :results verbatim code
  tm-ask-line "What is your name?" | cat
#+END_SRC

In the field of prompt engineering, this is
flipped on its head in that now we prompt an
AI.

The prompt is sent to an AI model and the
model generates a response stochastically.

#+NAME: prompt
#+BEGIN_SRC text -n :async :results verbatim code
  This is a conversation between Shane and an intelligent AI called Steve.
  - User: What is your name?
  - Computer: 
#+END_SRC

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :inb prompt
  # This command takes the above prompt and generates a response
  penf --pool -u pf-generic-completion-50-tokens/1 | sed -n 1p
#+END_SRC

* What is Emacs?
- It's what you're looking at currently on my screen.
- An IDE with a built-in programming language called Emacs Lisp.

** A typical emacs lisp function
#+BEGIN_SRC emacs-lisp -n :async :results verbatim code
  (+ 10 5)
#+END_SRC

** A Pen.el emacs lisp function
- Pen.el extends emacs with a set of functions
- Pen.el allows you to extend emacs with functions based on prompts
   
#+BEGIN_SRC emacs-lisp -n :async :results verbatim code
  (pf-very-witty-pick-up-lines-for-a-topic/1 "Florida")
#+END_SRC

* Pen.el project - Prompt engineering in emacs
** What is Pen.el?
- When a prompt function is run from Pen.el, the user is queried for inputs, the query is sent to the AI and its response is captured and then used
- You can use Pen.el to:
  - engineer your own prompt functions
  - extend Pen.el with prompt functions
  - as a prompting server to serve other applications
** Built-in library of prompt functions 
http://github.com/semiosis/prompts

e:$PROMPTS

*** =eli5=
e:$PROMPTS/eli5-explain-like-i-m-five-1.prompt

*** code generator from description
http://github.com/semiosis/prompts/blob/master/prompts/code-generator-from-description-1.prompt
e:$PROMPTS/code-generator-from-description-1.prompt

*** autofix code
http://github.com/semiosis/prompts/blob/master/prompts/autofix-code-2.prompt
e:$PROMPTS/autofix-code-2.prompt

*** asktutor
http://github.com/semiosis/prompts/blob/master/prompts/asktutor-3.prompt
e:$PROMPTS/asktutor-3.prompt

** How to build your own prompt functions

** Using prompts
*** For coding assistance
**** How to use
#+BEGIN_SRC emacs-lisp -n :async :results verbatim code
  (define-key pen-map (kbd "M-SPC e f") 'pf-get-an-example-of-the-usage-of-a-function/2)
#+END_SRC

pind:/root/.emacs.d/host/ilambda/hs/src/Main.hs

*** As a learning tool
**** Apostrope
**** Paracosm

* Blockchain
** DAO
** Currency
** NFTs
